name: Luna

packages:
  FakeWebKit:
    url: https://github.com/undeaDD/FakeWebKit
    branch: main

  SoraCore:
    url: https://github.com/cranci1/SoraCore
    branch: main

  Kingfisher:
    url: https://github.com/onevcat/Kingfisher
    from: 8.6.1

  MPVKit:
    url: https://github.com/mpvkit/MPVKit
    from: "0.40.0-xcode"

targets:
  Luna:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Luna
    settings:
      base:
        INFOPLIST_FILE: Luna/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 399LMK6Q2Y
        PRODUCT_BUNDLE_IDENTIFIER: me.cranci.solar
        PRODUCT_NAME: Luna
        IPHONEOS_DEPLOYMENT_TARGET: 17.0
        TARGETED_DEVICE_FAMILY: 1
        SWIFT_VERSION: 5.0
        CODE_SIGN_ENTITLEMENTS: Luna/Luna.entitlements
    dependencies:
      - package: FakeWebKit
        product: FakeWebKit
      - package: SoraCore
        product: SoraCore
      - package: Kingfisher
        product: Kingfisher
      - package: MPVKit
        product: MPVKit-GPL
