name: Build and Release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    name: Build IPA
    runs-on: macos-26

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode project
        run: xcodegen generate

      - name: Archive generated Xcode project
        run: zip -r Luna-xcodeproj.zip Luna.xcodeproj

      - name: Upload Xcode project artifact
        uses: actions/upload-artifact@v4
        with:
          name: Luna Xcode Project
          path: Luna-xcodeproj.zip

      - name: Build IPA
        run: ./ipabuild.sh ios

      - name: Compress IPA
        run: |
          cd build
          zip -r Luna.zip Luna.ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: Luna IPA
          path: build/Luna.zip
